sections = ["i want a simple button",
            'a simple paragraph',
            'a container with a centered message',
            'two buttons sepearted with some space between them',
            'github style like button',
            'a box containing two buttons one at left side and another at right side',
            'a circle with some margin',
            'a box with two columns',
            'a box with two rows',
            'a hero page with a title and a subtitle']